# https://prometheus-operator.dev/docs/operator/strategic-merge-patch/
# kubectl patch prometheus project-monitoring-prometheus --patch-file patches/prometheus-patch.yaml --type=merge
spec:
  containers:
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  - name: prometheus
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  initContainers:
  - name: init-config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
