apiVersion: v2
name: caas-project-monitoring
description: A Helm chart for Rancher Project Monitoring V3.
version: "1.3.0-rc0"
appVersion: "58.4.0"
icon: https://raw.githubusercontent.com/caas-team/caas-project-monitoring/main/logo.png
keywords:
- monitoring
dependencies:
- name: kube-prometheus-stack
  version: "58.4.0"
  repository: "https://prometheus-community.github.io/helm-charts"
sources:
- https://github.com/caas-team/caas-project-monitoring
- https://github.com/prometheus-community/helm-charts
maintainers:
- name: eumel8
  email: f.kloeker@telekom.de
  url: https://www.telekom.com
- name: puffitos
  email: bruno.bressi@telekom.de
  url: https://www.telekom.com
