{{ if .Values.caas.rbac.enabled }}
{{ $fullname := include "caas-project-monitoring.fullname" . }}
{{ $serviceaccount := include "caas-project-monitoring.serviceAccountName" . }}
{{ $monitornamespaces := include "caas-project-monitoring.namespace" . }}
{{ $releaseNamespace := include "caas-project-monitoring.namespace" . }} 
{{ if .Values.caas.projectNamespaces }}
{{ $monitornamespaces = printf "%s %s" $monitornamespaces .Values.caas.projectNamespaces }}
{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "caas-project-monitoring.labels" . | nindent 4 }}
  name: {{ include "caas-project-monitoring.serviceAccountName" . }}
  namespace: {{ include "caas-project-monitoring.namespace" . }}
{{- $namespaces := (splitList " " $monitornamespaces) }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}
  namespace: {{ $ns }}
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - view
- apiGroups: 
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceaccount }}
  namespace: {{ $releaseNamespace}}
{{ end }}
{{ end }}
